### ISSUE TITLE
problem with creating a WebSocket - data protocol error on server-side and disconnect

### ISSUE THREAD

**Issue by mafe** [Links2004/arduinoWebSockets#151]
After the IIS-8.5-server's response, I am getting disconnected at once.

```
"w3wp.exe" (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-131263553647222872): "C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data.OracleClient\v4.0_4.0.0.0__b77a5c561934e089\System.Data.OracleClient.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"w3wp.exe" (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-131263553647222872): "EntityFrameworkDynamicProxies-myGHL" geladen. 
"w3wp.exe" (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-131263553647222872): "EntityFrameworkDynamicProxies-Microsoft.AspNet.Identity.EntityFramework" geladen. 
public override void OnOpen()
WebSocketHandler::OnError(): Non-Fatal: System.Net.WebSockets.WebSocketException (0x83760002): Das Datenformat für den angegebenen Protokollvorgang ist ungültig
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__9.MoveNext()
WebSocketHandler::OnError(): Unhandled Exception: System.Net.WebSockets.WebSocketException (0x83760002): Das Datenformat für den angegebenen Protokollvorgang ist ungültig
```

DEBUG_WEBSOCKETS:

```
[WS-Client] asyncConnectOnce...<\n><\r><\n>
[WS-Client] connected to 192.168.1.28:80.<\n><\r><\n>
[WS-Client][sendHeader] sending header...<\n><\r><\n>
[WS-Client][sendHeader] handshake GET /WSHandler.ashx HTTP/1.1<\r><\n>
Connection: Upgrade<\r><\n>
Upgrade: websocket<\r><\n>
Sec-WebSocket-Version: 13<\r><\n>
Sec-WebSocket-Key: 0N6IBWaPduO4Od1YO43H/Q==<\r><\n>
Sec-WebSocket-Protocol: chat<\r><\n>
Host: 192.168.1.28:80<\r><\n>
Origin: file://<\r><\n>
User-Agent: WebSocket-Client<\r><\n>
<\r><\n>
<\r><\n>
<\r><\n>
[WS-Client][sendHeader] sending header... Done (25129us).<\n><\r><\n>
[WS-Client][handleHeader] RX: HTTP/1.1 101 Switching Protocols<\n><\r><\n>
[WS-Client][handleHeader] RX: Cache-Control: private<\n><\r><\n>
[WS-Client][handleHeader] RX: Upgrade: Websocket<\n><\r><\n>
[WS-Client][handleHeader] RX: Server: Microsoft-IIS/8.5<\n><\r><\n>
[WS-Client][handleHeader] RX: X-AspNet-Version: 4.0.30319<\n><\r><\n>
[WS-Client][handleHeader] RX: Sec-WebSocket-Accept: EysVSrl9cJtsNSnGjXluxDb67ZE=<\n><\r><\n>
[WS-Client][handleHeader] RX: Connection: Upgrade<\n><\r><\n>
[WS-Client][handleHeader] RX: X-Powered-By: ASP.NET<\n><\r><\n>
[WS-Client][handleHeader] RX: Date: Fri, 16 Dec 2016 09:51:35 GMT<\n><\r><\n>
[WS-Client][handleHeader] Header read fin.<\n><\r><\n>
[WS-Client][handleHeader] Client settings:<\n><\r><\n>
[WS-Client][handleHeader]  - cURL: /WSHandler.ashx<\n><\r><\n>
[WS-Client][handleHeader]  - cKey: 0N6IBWaPduO4Od1YO43H/Q==<\n><\r><\n>
[WS-Client][handleHeader] Server header:<\n><\r><\n>
[WS-Client][handleHeader]  - cCode: 101<\n><\r><\n>
[WS-Client][handleHeader]  - cIsUpgrade: 1<\n><\r><\n>
[WS-Client][handleHeader]  - cIsWebsocket: 1<\n><\r><\n>
[WS-Client][handleHeader]  - cAccept: EysVSrl9cJtsNSnGjXluxDb67ZE=<\n><\r><\n>
[WS-Client][handleHeader]  - cProtocol: chat<\n><\r><\n>
[WS-Client][handleHeader]  - cExtensions: <\n><\r><\n>
[WS-Client][handleHeader]  - cVersion: 0<\n><\r><\n>
[WS-Client][handleHeader]  - cSessionId: <\n><\r><\n>
[WS-Client][handleHeader] Websocket connection init done.<\n><\r><\n>
[WS][0][headerDone] Header Handling Done (1610616576us).<\n><\r><\n>
[WS][0][handleWebsocketCb]: t1<\n><\r><\n>
[WS][0][handleWebsocketWaitFor]: t0<\n><\r><\n>
[WS][0][handleWebsocketWaitFor]: t1<\n><\r><\n>
[WS][0][handleWebsocketWaitFor]: t2<\n><\r><\n>
[WS][0][handleWebsocketWaitFor]: t3<\n><\r><\n>
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0<\n><\r><\n>
[WS][0][readCb]: t0<\n><\r><\n>
[WS][0][readCb]: t1<\n><\r><\n>
[WS][0][handleWebsocketWaitFor]: t99<\n><\r><\n>
DEBUG_WEBSOCKETCLIENT:85945ms:src\WsClient.cpp:50:WebSocketClientClass::webSocketEvent:WStype_CONNECTED:payload=/WSHandler.ashx<\r><\n>
[WS-Client] connection to 192.168.1.28:80 Faild<\n><\r><\n>

```

Can you help me finding out, what causes the immediate disconnect?

**Comment by Links2004** [comment]
the debug out from ```handleWebsocketWaitFor``` and ```readCb``` looks strange.
the code not print any ```t0```, ```t1```, ....
have you done any modifications?

https://github.com/Links2004/arduinoWebSockets/blob/529a86cc26cff78896f6627bd9475d6060a36df5/src/WebSockets.cpp#L293-L407

I think the ```[WS-Client] connection to 192.168.1.28:80 Fail``` is from the connection retry after the Server is crashed.

the Header itself look ok, the ISS not send all WS headers but the necessary ```Sec-WebSocket-Accept``` is there,
you can try not set the ```Sec-WebSocket-Protocol``` have seen some other servers implementations which not like this.
simple set it to "" and the header will not be send.

**Comment by mafe** [comment]
Thanks for your fast response Markus.

I made the t0...99 modifications for stepping through the code and get any clue on where it fails.
I left the protocol open, too, but without success.

I think, it could be something on parsing after HTTP:SwitchingProtocols 101.
When I use beginIOSocket it holds the connection open. I had to do some modifications, for example, removing transport parameter on the GET-Request.

When I use begin for having a default WebSocket connections, it will disconnect after the server responded like I posted.

Is there a big difference in using beginIOSocket and begin? Is it a polling issue?

**Comment by Links2004** [comment]
```beginSocketIO``` is for a server running http://socket.io/ for a normal Websocket server you need ```begin```, may the IIS need a Websocket ping ```webSocket.sendPing();```.

socket.io is a protocol ontop of Websockets.
https://github.com/socketio/socket.io-protocol

there is no "polling", to goal of websockets is to not need to poll any data.
normally the client or the server can send data at any time when the header handling is done (connection established).
but none of them is forced to send anything.
it is good practise to send a Ping when there is longer periods without data to detect the connection state, from the RFC point of view this is optional.

The .NET error is totally cryptic for me.

-- 
Was .NET unter Protokollvorgang und Datenformat im Zusammenhang mit Websockets versteht ist leider unklar.

**Comment by Links2004** [comment]
feel free to reopen when this still is a Issue.
may retest with the latest git version.

**Comment by mafe** [comment]
I merged with latest git commits and it is working fine, now.
Thanks Markus.
