### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mo121Montazeri** [Links2004/arduinoWebSockets#49]
Arduino: 1.6.7 (Mac OS X), Board: "Arduino/Genuino Uno"

/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp: In member function 'void WebSockets::sendFrame(WSclient_t*, WSopcode_t, uint8_t*, size_t, bool, bool, bool)':
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:182:34: warning: right shift count >= width of type [enabled by default]
         *headerPtr = ((length >> 24) & 0xFF);

                                  ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:184:34: warning: right shift count >= width of type [enabled by default]
         *headerPtr = ((length >> 16) & 0xFF);

                                  ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp: In member function 'bool WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)':
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:299:87: error: 'bind' is not a member of 'std'
     readCb(client, &client->cWsHeader[client->cWsRXsize], (size - client->cWsRXsize), std::bind([](WebSockets * server, size_t size, WSclient_t * client, bool ok) {

                                                                                       ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:310:25: error: 'std::placeholders' has not been declared
     }, this, size, std::placeholders::_1, std::placeholders::_2));

                         ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:310:48: error: 'std::placeholders' has not been declared
     }, this, size, std::placeholders::_1, std::placeholders::_2));

                                                ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp: In member function 'void WebSockets::handleWebsocketCb(WSclient_t*)':
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:359:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
             header->payloadLen = 0xFFFFFFFF;

                                ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:361:47: warning: left shift count >= width of type [enabled by default]
             header->payloadLen = buffer[4] << 24 | buffer[5] << 16 | buffer[6] << 8 | buffer[7];

                                               ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:361:65: warning: left shift count >= width of type [enabled by default]
             header->payloadLen = buffer[4] << 24 | buffer[5] << 16 | buffer[6] << 8 | buffer[7];

                                                                 ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:394:53: error: 'bind' is not a member of 'std'
         readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, placeholders::_1, std::placeholders::_2, payload));

                                                     ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:394:108: error: 'placeholders' has not been declared
         readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, placeholders::_1, std::placeholders::_2, payload));

                                                                                                            ^
/Users/iMohammad/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:394:131: error: 'std::placeholders' has not been declared
         readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, placeholders::_1, std::placeholders::_2, payload));

                                                                                                                                   ^
exit status 1
Error compiling.
 Error downloading http://downloads.arduino.cc/libraries/library_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/libraries/library_index.json
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onUpdatePressed$13(LibraryManagerUI.java:205)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/libraries/library_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.JsonDownloader.download(JsonDownloader.java:49)
	at cc.arduino.contributions.GZippedJsonDownloader.download(GZippedJsonDownloader.java:59)
	at cc.arduino.contributions.libraries.LibraryInstaller.updateIndex(LibraryInstaller.java:66)
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onUpdatePressed$13(LibraryManagerUI.java:202)
	... 1 more
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:166)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:123)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by Links2004** [comment]
the latest git is not compatible with AVR/ATmega, check ATmega branch.
Arduino for AVR not supports std namespace of c++,
 so its currently not compatible.

https://github.com/Links2004/arduinoWebSockets/tree/ATmega
