### ISSUE TITLE
Cant build on Wemos D1 board

### ISSUE THREAD

**Issue by ilomon10** [Links2004/arduinoWebSockets#562]
I use PlatformIO IDE for editor and here my project config

```ini
[env:d1]
platform = espressif8266
board = d1
framework = arduino

monitor_speed = 115200

lib_deps = 
  links2004/WebSockets@^2.2.1
  bblanchon/ArduinoJson@^6.16.1
```

i got error `*** [.pio\build\d1\lib646\Ethernet_ID872\Ethernet.cpp.o] Error 1` at the end of build and more ethernet like error on every example but i didnt use any ethernet module and followed by most common warning `#define ntohl(x) lwip_ntohl(x)`

example i ever tired:
https://github.com/Links2004/arduinoWebSockets/tree/master/examples/esp8266/WebSocketClient
https://github.com/Links2004/arduinoWebSockets/tree/master/examples/esp8266/WebSocketClientSocketIO

**Comment by Links2004** [comment]
I only had problems with the `lib_deps` you posted, 
`WebSockets` needs to be `arduinoWebSockets`
and i needed to use the short hash as verison.
but the build is working fine.

```
[env:d1]
platform = espressif8266
board = d1
framework = arduino

monitor_speed = 115200

lib_deps = 
  links2004/arduinoWebSockets@b3c5348
  bblanchon/ArduinoJson@d04669d
```

```
Indexing .pio/build/d1/libFrameworkArduino.a
Linking .pio/build/d1/firmware.elf
Building .pio/build/d1/firmware.bin
Retrieving maximum program size .pio/build/d1/firmware.elf
Checking size .pio/build/d1/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [====      ]  35.1% (used 28720 bytes from 81920 bytes)
Flash: [====      ]  37.6% (used 393044 bytes from 1044464 bytes)
Creating BIN file ".pio/build/d1/firmware.bin" using ".pio/build/d1/firmware.elf"
============================================ [SUCCESS] Took 11.38 seconds ============================================
```

**Comment by ilomon10** [comment]
how to install that library like your version config
sorry its my first time use platformio

**Comment by Links2004** [comment]
in vs-code i only change the `platformio.ini` and press build, 
the download / git checkout will happen automatically.

**Comment by ilomon10** [comment]
i tried delete all installed library and run CLI lib install

Still getting error
```bash
$ platformio lib install
Library Storage: C:\Users\ilomo\Documents\PlatformIO\Projects\SmartMeter\.pio\libdeps\d1
Error: Traceback (most recent call last):
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\commands\lib\command.py", line 170, in lib_install
    lm.install(library, silent=silent, force=force)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 49, in install
    spec, silent=silent, skip_dependencies=skip_dependencies, force=force
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 65, in _install
    spec = self.ensure_spec(spec)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 100, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 119, in __init__
    self._parse(raw)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 221, in _parse
    raw = parser(raw)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 238, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 162, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\semantic_version\base.py", line 618, in __init__
    self.clause = self._parse_to_clause(expression)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1014, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "c:\users\ilomo\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1034, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block 'b3c5348'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

**Comment by ilomon10** [comment]
@Links2004 thank you for fast respond, now it fixed with add complete latest repo comit url and it gets done when i rebuild
```ini
[env:d1]
platform = espressif8266
board = d1
framework = arduino

monitor_speed = 115200

lib_deps = 
  https://github.com/Links2004/arduinoWebSockets.git#b3c5348e9b11e50069e00bc6fb53a5a62bf70f11
  https://github.com/bblanchon/ArduinoJson.git#d04669d0cc2569d9fc2f38f93c0912fd0a42538c
```
