### ISSUE TITLE
Inconsistent Payload Data

### ISSUE THREAD

**Issue by gitZui** [Links2004/arduinoWebSockets#693]
Hi!
I don't know if this question belongs here, but I miss some information on how the payload pointer for received data needs to be used.
I have the problem that the memory at it's address is altered, before I can process the data.
So I would like to understand how the payload is stored. If its memory is allocated when a message is received, when and how is it released and how do I make sure that it is not released before the data is processed?
I have the feeling that I am missing something crucial.

**Comment by Tusharkumar0012** [comment]
Sorry not your soln . But 
Can you tell me how to send data from esp8266 socketio client to node server . .
.sendTEXT  is not working . 
.sendEVENT i dont know how to use . If i am putting json in that node server says invalid payload and disconnects .

**Comment by Links2004** [comment]
@gitZui can you post your code?

the pointer / the data is valide as long `webSocketEvent` has not returned.
after the return the pointer is invalide, and the OS may places other data there.
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSockets.cpp#L518-L520

**Comment by Tusharkumar0012** [comment]
/*
 * WebSocketClientSocketIO.ino     
 *
 *  Created on: 06.06.2016
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <ArduinoJson.h>

#include <WebSocketsClient.h>
#include <SocketIOclient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
SocketIOclient socketIO;

#define USE_SERIAL Serial

void socketIOEvent(socketIOmessageType_t type, uint8_t * payload, size_t length) {
    switch(type) {
        case sIOtype_DISCONNECT:
            USE_SERIAL.printf("[IOc] Disconnected!\n");
            break;
        case sIOtype_CONNECT:
            USE_SERIAL.printf("[IOc] Connected to url: %s\n", payload);

            // join default namespace (no auto join in Socket.IO V3)
            socketIO.send(sIOtype_CONNECT, "/");
            break;
        case sIOtype_EVENT:
            USE_SERIAL.printf("[IOc] get event: %s\n", payload);
            break;
        case sIOtype_ACK:
            USE_SERIAL.printf("[IOc] get ack: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_ERROR:
            USE_SERIAL.printf("[IOc] get error: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_EVENT:
            USE_SERIAL.printf("[IOc] get binary: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_ACK:
            USE_SERIAL.printf("[IOc] get binary ack: %u\n", length);
            hexdump(payload, length);
            break;
            
    }
}

void setup()
{
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    // disable AP
    if(WiFi.getMode() & WIFI_AP) {
        WiFi.softAPdisconnect(true);
    }

    WiFiMulti.addAP("unKNOWN", "KHEMchandra2.4");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    String ip = WiFi.localIP().toString();
    USE_SERIAL.printf("[SETUP] WiFi Connected %s\n", ip.c_str());

    // server address, port and URL
    socketIO.beginSSL("192.168.**.***", 443 , "/socket.io/?EIO=4" , "818bc7329e5e336d420f441e592d527d1265bc08");

    // event handler
    socketIO.onEvent(socketIOEvent);
}

int i=1 ;

void loop()
{
    socketIO.loop();
    
            if(i==1)
            {
            String output1 ; 
            StaticJsonDocument<200> doc1;
            doc1["hello"] = "world";
            serializeJson(doc1, output1);       
            socketIO.sendEVENT(output1);
            USE_SERIAL.println(output1);
           // i = i+1 ;
            }

/* if i do 
socketIO.sendEVENT("\ANYTHING"); 
                 or
socketIO.sendEVENT("\"ANYTHING\"");
           or
 String o = "{\"command\":\"togglePins\",\"pin\":4,\"state\":1,\"secret\":547456}" ; 
           socketIO.sendEVENT(o);
*/ gives same error
}

 IT COMPILES FINE AND DOES NOT GIVE ANY ERROR ON SERVER SIDE BUT RECIEVES NOTHING */
}


----------------------------------------------NODE JS TERMINAL -----------------------------------------------------------------------
user disconnected
A new user just connected
Missing error handler on `socket`.
Error: invalid payload
    at Decoder.decodeString (K:\Users\Tushar\Desktop\EP\esp2\node_modules\socket.io-parser\dist\index.js:201:23)
    at Decoder.add (K:\Users\Tushar\Desktop\EP\esp2\node_modules\socket.io-parser\dist\index.js:105:27)
    at Client.ondata (K:\Users\Tushar\Desktop\EP\esp2\node_modules\socket.io\dist\client.js:180:26)
    at Socket.emit (events.js:375:28)
    at Socket.onPacket (K:\Users\Tushar\Desktop\EP\esp2\node_modules\engine.io\lib\socket.js:123:14)
    at WebSocket.emit (events.js:375:28)
    at WebSocket.onPacket (K:\Users\Tushar\Desktop\EP\esp2\node_modules\engine.io\lib\transport.js:86:10)
    at WebSocket.onData (K:\Users\Tushar\Desktop\EP\esp2\node_modules\engine.io\lib\transport.js:96:10)
    at WebSocket.onData (K:\Users\Tushar\Desktop\EP\esp2\node_modules\engine.io\lib\transports\websocket.js:56:11)
    at WebSocket.emit (events.js:375:28)
user disconnected
//it connnects then gives error then reconnects .
    -----------------------------------------------------------------------------------------------------------------------------------------


**************************************************node js socketio server**********************************************************
const path = require("path");
const express = require("express");
const socketIO = require('socket.io');
const fs = require("fs");
const https = require("https");
const { clear } = require("console");

var privateKey = fs.readFileSync(path.join(__dirname , 'cert' , 'key.pem'));
var certificate = fs.readFileSync(path.join(__dirname , 'cert' , 'cert.pem'));
var credentials = { key: privateKey , cert: certificate };
console.log(__dirname );
const HTTPS_PORT = 443;
const app = express();
const httpsServer = https.createServer(credentials , app);

let io = socketIO(httpsServer);
io.on('connection',(socket)=>
{
    console.log("A new user just connected");
    socket.emit("this is node server")
    
   socket.on('message',(message)=>
    {
        console.log(message);
      }); 

    socket.on('disconnect',()=>
    {
        console.log("user disconnected");
    });
    
    socket.on("toEspFromChrome", (data) => 
    {
        io.emit("toEsp" , data) ;
        console.log(data);
      });

     
})

//app.use(express.static("."));
app.get("/", (req, res) => res.sendFile(path.resolve(__dirname, "index.html")));
httpsServer.listen(HTTPS_PORT, () => console.log(`HTTPS server listening at ${HTTPS_PORT}`));  
**************************************************************************************************************************************

**Comment by Links2004** [comment]
looks to me like you build a JSON with the wrong Format for socket.io.
socket.io expects a JSON array where the first element is the event name, and the following are the args of the callback on the server side.

working example:
https://github.com/Links2004/arduinoWebSockets/blob/27f86a10ad3571c4ec454a7e47739539b8c19e01/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L135-L165

**Comment by Tusharkumar0012** [comment]
I tried that example sir but i am not getting any message in socket io server . Should i listen for "now" event in my server according to this example .
Thanks very much sir for your reply .

**Comment by Tusharkumar0012** [comment]
Sorry @gitZui for posting my query here . I just joined github so..
